import { expect, test } from "@playwright/test";
import type { MovementIntent } from "../../src/domain/plan-contract";
import { fixtureOptions } from "./plan-fixtures";

test.use({ serviceWorkers: "block", timezoneId: "Asia/Kolkata" });
const NORTH = { id: "fictional-north", name: "Fictional North Gate", kind: "entrance", lat: 28.6951, lon: 77.2143 };
const VENUE = { id: "fictional-venue", name: "Fictional Evening Venue", kind: "venue", lat: 28.6991, lon: 77.2183 };

async function forbidGps(page: import("@playwright/test").Page) {
  let calls = 0;
  await page.exposeBinding("recordForbiddenGps", () => { calls++; });
  await page.addInitScript(() => {
    (window as Window & { geoCalls?: number }).geoCalls = 0;
    Object.defineProperty(navigator.geolocation, "getCurrentPosition", { configurable: true, value: () => { void (window as unknown as Window & { recordForbiddenGps: () => Promise<void> }).recordForbiddenGps(); (window as Window & { geoCalls?: number }).geoCalls!++; throw new Error("Unexpected GPS request"); } });
    Object.defineProperty(navigator.geolocation, "watchPosition", { configurable: true, value: () => { void (window as unknown as Window & { recordForbiddenGps: () => Promise<void> }).recordForbiddenGps(); (window as Window & { geoCalls?: number }).geoCalls!++; throw new Error("Unexpected GPS watch"); } });
  });
  return () => calls;
}
async function choosePlace(page: import("@playwright/test").Page, label: "From" | "To", place: typeof NORTH) {
  await page.getByRole("textbox", { name: label, exact: true }).fill(place.name);
  await page.getByRole("button", { name: "Find", exact: true }).nth(label === "From" ? 0 : 1).click();
  await page.getByRole("button", { name: new RegExp(place.name) }).click();
}

// Browser clock + graph/search are deterministic fixtures. Nothing establishes a real run path.
test("S1 first-time guest chooses a mapped 4:45 AM run loop without GPS, progresses, reloads and confirms arrival", async ({ page, context }) => {
  await context.clearPermissions();
  const geoCalls = await forbidGps(page);
  const today = new Intl.DateTimeFormat("sv-SE", { timeZone: "Asia/Kolkata", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());
  const dawn = new Date(`${today}T04:45:00+05:30`);
  await page.clock.setFixedTime(dawn);
  await page.route("**/api/mira/intent", (route) => route.fulfill({ json: { hints: null } }));
  await page.route("**/api/geo/search", (route) => route.fulfill({ json: { places: [NORTH] } }));
  let tripPosts = 0, optionRequests = 0;
  await page.route("**/api/trips", async (route) => { if (route.request().method() === "POST") tripPosts++; await route.continue(); });
  await page.route("**/api/plan/options", async (route) => {
    const { intent } = route.request().postDataJSON() as { intent: MovementIntent };
    expect(intent.loop).toBe(true); expect(intent.mode).toBe("walk"); expect(intent.loopTarget).toEqual({ kind: "duration", value: 30 }); expect(intent.paceMinutesPerKm).toBe(7);
    optionRequests++;
    await route.fulfill({ json: fixtureOptions(intent, [{ id: "fixture-loop-a", label: "Fixture mapped run loop", minutes: 30, meters: 4280 }, { id: "fixture-loop-b", label: "Fixture out-and-back", minutes: 28, meters: 4000 }]) });
  });
  await page.goto("/plan/legs");
  await page.getByLabel("What do you want to do?").fill("A 30-minute run at 4:45 AM");
  await page.getByRole("checkbox", { name: "Return to my starting point (loop)" }).check();
  await choosePlace(page, "From", NORTH);
  await page.getByLabel("Loop duration (minutes)").fill("29"); // the field shows 30 by default; change it so the target is chosen explicitly
  await page.getByLabel("Loop duration (minutes)").fill("30");
  await page.getByLabel("Pace (min / km)").fill("8");
  await page.getByLabel("Pace (min / km)").fill("7");
  const local = await page.evaluate(() => new Intl.DateTimeFormat("sv-SE", { year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).format(new Date()).replace(" ", "T"));
  await page.getByLabel("Planned local time").fill(local);
  await page.getByLabel("Time zone (IANA)").fill(await page.evaluate(() => Intl.DateTimeFormat().resolvedOptions().timeZone));
  await page.getByRole("button", { name: "Compare my options" }).click();
  await page.getByRole("button", { name: /Fixture out-and-back/ }).click();
  await expect(page.getByRole("button", { name: /Fixture out-and-back/ })).toHaveAttribute("aria-pressed", "true");
  await expect(page.getByRole("img", { name: /Route overview: Fixture out-and-back/ })).toBeVisible();
  await page.getByRole("button", { name: "Start chosen journey" }).click();
  await expect(page.getByText("Only you can see this tab journey.", { exact: false })).toBeVisible();
  expect(tripPosts).toBe(0);
  await page.getByRole("button", { name: "Confirm start" }).click();
  await expect(page).toHaveURL(/\/trip\/local$/);
  await expect(page.getByRole("region", { name: "Manual progress" })).toContainText("Mira has not alerted anyone");
  await page.getByRole("slider", { name: /Manual progress/ }).fill("50");
  await expect(page.getByRole("slider", { name: /Manual progress/ })).toHaveValue("50");
  const timerBeforeCheckIn = await page.evaluate(() => sessionStorage.getItem("mira.local-check-in.v1"));
  await page.getByRole("button", { name: "Check in privately" }).click();
  await expect(page.getByRole("status").filter({ hasText: "Checked in at" })).toContainText("journey is still active; nobody was notified");
  expect(await page.evaluate(() => sessionStorage.getItem("mira.local-check-in.v1"))).toBe(timerBeforeCheckIn);
  await expect(page.getByRole("heading", { name: "You’ve arrived." })).toHaveCount(0);
  await page.getByText("Mapped route reference", { exact: true }).click();
  await expect(page.getByText("Fictional pedestrian segment", { exact: false })).toBeVisible();
  await page.getByRole("button", { name: "I need options" }).click();
  await expect(page.getByRole("dialog", { name: "Right now" }).getByLabel("Immediate Emergency action").getByRole("button", { name: "Emergency options" })).toBeVisible();
  await page.getByRole("dialog", { name: "Right now" }).getByRole("button", { name: "Close", exact: true }).click();
  await page.reload();
  await expect(page.getByRole("img", { name: /Route overview: Fixture out-and-back/ })).toBeVisible();
  await expect(page.getByRole("slider", { name: /Manual progress/ })).toHaveValue("50");
  await expect(page.getByRole("status").filter({ hasText: "Checked in at" })).toContainText("journey is still active; nobody was notified");
  expect(optionRequests).toBeGreaterThan(1);
  await page.goto("/trips");
  await page.getByRole("link", { name: "Resume private journey" }).click();
  await page.getByRole("button", { name: "I’m here — confirm arrival" }).click();
  await expect(page.getByRole("heading", { name: "You’ve arrived." })).toBeVisible();
  await expect(page.getByRole("status").filter({ hasText: "Arrival was confirmed by you" })).toContainText("Nothing was sent to contacts");
  expect(await page.evaluate(() => sessionStorage.getItem("mira.local-check-in.v1"))).toBeNull();
  expect(await page.evaluate(() => (window as Window & { geoCalls?: number }).geoCalls)).toBe(0);
  expect(tripPosts).toBe(0); expect(geoCalls()).toBe(0);
});

test("S4 no-GPS night out completes arrival then reviews and explicitly starts a separate private midnight return", async ({ page }) => {
  const geoCalls = await forbidGps(page);
  const today = new Intl.DateTimeFormat("sv-SE", { timeZone: "Asia/Kolkata", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());
  const evening = new Date(`${today}T21:00:00+05:30`);
  const midnight = new Date(evening.getTime() + 190 * 60_000);
  await page.clock.setFixedTime(evening);
  await page.route("**/api/geo/search", (route) => route.fulfill({ json: { places: [(route.request().postDataJSON() as { q: string }).q.includes("Venue") ? VENUE : NORTH] } }));
  let tripPosts = 0;
  await page.route("**/api/trips", async (route) => { if (route.request().method() === "POST") tripPosts++; await route.continue(); });
  await page.route("**/api/plan/options", (route) => route.fulfill({ json: fixtureOptions((route.request().postDataJSON() as { intent: MovementIntent }).intent) }));
  await page.goto("/plan/legs");
  await page.getByLabel("What do you want to do?").fill("Night out at fictional venue");
  await choosePlace(page, "From", NORTH); await choosePlace(page, "To", VENUE);
  const format = (d: Date) => new Intl.DateTimeFormat("sv-SE", { timeZone: "Asia/Kolkata", year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).format(d).replace(" ", "T");
  const zone = await page.evaluate(() => Intl.DateTimeFormat().resolvedOptions().timeZone);
  await page.getByLabel("Planned local time").fill(format(evening)); await page.getByLabel("Time zone (IANA)").fill(zone);
  await page.getByRole("button", { name: "Return & legs" }).click();
  await page.getByRole("button", { name: "Add return leg" }).click();
  await expect(page.getByLabel("Leg 2 local departure")).toHaveValue("");
  await page.getByLabel("Leg 2 local departure").fill(format(midnight)); await page.getByLabel("Leg 2 IANA time zone").fill(zone);
  await page.getByRole("button", { name: /^2\s*Options$/ }).click();
  await page.getByRole("button", { name: "Start chosen journey" }).click(); await page.getByRole("button", { name: "Confirm start" }).click();
  await expect(page).toHaveURL(/\/trip\/local$/);
  await page.getByRole("button", { name: "I’m here — confirm arrival" }).click();
  await expect(page.getByRole("heading", { name: "You’ve arrived." })).toBeVisible();
  await page.getByRole("button", { name: "Review return journey" }).click();
  await expect(page).toHaveURL(/\/plan(\/legs)?\?planStep=options$/);
  await expect(page.getByRole("button", { name: /^2\s*Options$/ })).toHaveAttribute("aria-current", "step");
  await expect(page.getByRole("region", { name: "Plan options" })).toContainText(format(midnight).replace("T", " "));
  await expect(page.getByText(`Return to ${NORTH.name}`, { exact: true })).toBeVisible();
  const returnDraft = await page.evaluate(() => JSON.parse(sessionStorage.getItem("mira.plan.v1") ?? "null")?.draft);
  expect(returnDraft.origin.query).toBe(VENUE.name);
  expect(returnDraft.destination.query).toBe(NORTH.name);
  expect(returnDraft.departureLocal).toBe(format(midnight));
  expect(returnDraft.timeZone).toBe(zone);
  expect(returnDraft.legs[0].label).toBe("Night out at fictional venue");
  expect(returnDraft.legs[0].departureLocal).toBe(format(evening));
  expect(await page.evaluate(() => sessionStorage.getItem("mira.local-check-in.v1"))).toBeNull();
  expect(tripPosts).toBe(0); // review alone starts neither a timer nor a server journey
  await page.clock.setFixedTime(midnight);
  await page.getByRole("button", { name: "Start chosen journey" }).click();
  expect(await page.evaluate(() => sessionStorage.getItem("mira.local-check-in.v1"))).toBeNull();
  await page.getByRole("button", { name: "Confirm start" }).click();
  await expect(page).toHaveURL(/\/trip\/local$/);
  await expect(page.getByRole("heading", { name: NORTH.name })).toBeVisible();
  await page.getByRole("button", { name: "I’m here — confirm arrival" }).click();
  await expect(page.getByRole("status").filter({ hasText: "Arrival was confirmed by you" })).toBeVisible();
  expect(tripPosts).toBe(0); expect(geoCalls()).toBe(0); expect(await page.evaluate(() => (window as Window & { geoCalls?: number }).geoCalls)).toBe(0);
});

test("missing loop provider keeps a guest manual check-in usable and ending early never claims arrival", async ({ page }) => {
  const geoCalls = await forbidGps(page);
  await page.route("**/api/geo/search", (route) => route.fulfill({ json: { places: [NORTH] } }));
  await page.route("**/api/plan/options", (route) => {
    const answer = fixtureOptions((route.request().postDataJSON() as { intent: MovementIntent }).intent);
    return route.fulfill({ json: { ...answer, state: "missing", options: [], detail: "Fixture: no pedestrian graph for this area." } });
  });
  let tripPosts = 0;
  await page.route("**/api/trips", async (route) => { if (route.request().method() === "POST") tripPosts++; await route.continue(); });
  await page.goto("/plan/legs");
  await page.getByLabel("What do you want to do?").fill("Fictional evening loop");
  await choosePlace(page, "From", NORTH);
  await page.getByRole("checkbox", { name: "Return to my starting point (loop)" }).check();
  await page.getByRole("button", { name: "Compare my options" }).click();
  await expect(page.getByRole("region", { name: "Plan options" })).toContainText("no pedestrian graph");
  await expect(page.getByRole("img", { name: /Route overview/ })).toHaveCount(0);
  await page.getByLabel("Check in after (minutes)").fill("20");
  await page.getByRole("button", { name: "Start manual journey" }).click();
  await page.getByRole("button", { name: "Confirm start" }).click();
  await expect(page).toHaveURL(/\/trip\/local$/);
  await expect(page.getByRole("region", { name: "Manual progress" })).toContainText("20");
  await page.reload();
  await expect(page.getByRole("region", { name: "Manual progress" })).toBeVisible();
  await expect(page.getByRole("slider", { name: /Manual progress/ })).toHaveCount(0);
  await page.getByRole("button", { name: "End journey early" }).click();
  await expect(page.getByRole("heading", { name: "Journey ended." })).toBeVisible();
  await expect(page.getByRole("status").filter({ hasText: "not recorded as arrival" })).toBeVisible();
  expect(await page.evaluate(() => sessionStorage.getItem("mira.local-check-in.v1"))).toBeNull();
  expect(tripPosts).toBe(0); expect(geoCalls()).toBe(0);
});

test("missing place and service providers keep an arrival deadline usable through explicitly confirmed manual planning", async ({ page }) => {
  const geoCalls = await forbidGps(page);
  await page.clock.setFixedTime(new Date("2026-10-03T18:00:00Z"));
  let tripPosts = 0;
  await page.route("**/api/trips", async (route) => { if (route.request().method() === "POST") tripPosts++; await route.continue(); });
  await page.goto("/plan/legs");
  await page.getByLabel("What do you want to do?").fill("Fictional late terminal arrival");
  await page.getByRole("textbox", { name: "From", exact: true }).fill("Fictional remote terminal");
  await page.getByRole("textbox", { name: "To", exact: true }).fill("Fictional remote hotel");
  await page.getByRole("combobox", { name: "Timing", exact: true }).selectOption("arrive_by");
  await page.getByRole("combobox", { name: "Mode", exact: true }).selectOption("ride");
  const arrival = await page.evaluate(() => new Intl.DateTimeFormat("sv-SE", { year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).format(new Date(Date.now() + 30 * 60_000)).replace(" ", "T"));
  await page.getByLabel("Planned local time").fill(arrival);
  await page.getByLabel("Time zone (IANA)").fill("Asia/Kolkata");
  await page.getByRole("button", { name: "Compare my options" }).click();
  await expect(page.getByRole("region", { name: "Plan options" })).toContainText("Your current location will not be substituted");
  await expect(page.getByText(/With your 30-minute manual estimate, depart about/)).toBeVisible();
  await page.getByRole("button", { name: "Start manual journey" }).click();
  await page.getByRole("button", { name: "Confirm start" }).click();
  await expect(page.getByRole("status").filter({ hasText: "Confirm the named places directly" })).toBeVisible();
  await page.getByRole("checkbox", { name: /I confirmed the named places directly/ }).check();
  await page.getByRole("button", { name: "Start manual journey" }).click();
  await page.getByRole("button", { name: "Confirm start" }).click();
  await expect(page).toHaveURL(/\/trip\/local$/);
  await expect(page.getByRole("heading", { name: "Fictional remote hotel", exact: true })).toBeVisible();
  const retained = await page.evaluate(() => JSON.parse(sessionStorage.getItem("mira.plan.v1")!).draft);
  expect(retained.timeKind).toBe("arrive_by"); expect(retained.departureLocal).toBe(arrival);
  await page.getByRole("button", { name: "End journey early" }).click();
  await expect(page.getByRole("heading", { name: "Journey ended." })).toBeVisible();
  expect(geoCalls()).toBe(0); expect(tripPosts).toBe(0);
});

// Search and missing graph responses are fictional fixtures, not provider coverage evidence.
test("an active missing-provider manual journey changes only after origin confirmation and keeps its original start", async ({ page, context }) => {
  await context.clearPermissions();
  const geoCalls = await forbidGps(page);
  const startedAt = new Date("2026-10-03T18:00:00+05:30").getTime();
  const confirmedAt = startedAt + 5 * 60_000;
  await page.clock.setFixedTime(startedAt);
  await page.route("**/api/geo/search", (route) => route.fulfill({ json: { places: [(route.request().postDataJSON() as { q: string }).q.includes("Venue") ? VENUE : NORTH] } }));
  await page.route("**/api/plan/options", (route) => {
    const answer = fixtureOptions((route.request().postDataJSON() as { intent: MovementIntent }).intent);
    return route.fulfill({ json: { ...answer, state: "missing", options: [], detail: "Fixture: no pedestrian graph for this area." } });
  });
  let tripPosts = 0;
  await page.route("**/api/trips", async (route) => { if (route.request().method() === "POST") tripPosts++; await route.continue(); });
  const readTimer = () => page.evaluate(() => JSON.parse(sessionStorage.getItem("mira.local-check-in.v1") ?? "null"));
  const readChoice = () => page.evaluate(() => JSON.parse(sessionStorage.getItem("mira.local-journey-choice.v1") ?? "null"));

  await page.goto("/plan/legs");
  await page.getByLabel("What do you want to do?").fill("Fictional evening loop");
  await choosePlace(page, "From", NORTH);
  await page.getByRole("checkbox", { name: "Return to my starting point (loop)" }).check();
  await page.getByLabel("Planned local time").fill("2026-10-03T18:00");
  await page.getByLabel("Time zone (IANA)").fill("Asia/Kolkata");
  await page.getByRole("button", { name: "Compare my options" }).click();
  await expect(page.getByRole("region", { name: "Plan options" })).toContainText("no pedestrian graph");
  await page.getByLabel("Check in after (minutes)").fill("20");
  await page.getByRole("button", { name: "Start manual journey" }).click();
  await page.getByRole("button", { name: "Confirm start" }).click();
  await expect(page).toHaveURL(/\/trip\/local$/);
  await page.getByRole("button", { name: "Check in privately" }).click();
  const originalTimer = await readTimer();
  const originalChoice = await readChoice();
  expect(originalTimer).toEqual({ version: 1, startedAt, dueAt: startedAt + 20 * 60_000 });
  expect(originalChoice.checkedInAt).toBe(startedAt);

  await page.clock.setFixedTime(confirmedAt);
  await page.getByRole("link", { name: "Review or change this journey" }).click();
  await expect(page).toHaveURL(/\/plan\/legs$/);
  await page.getByLabel("What do you want to do?").fill("Fictional continued loop");
  await choosePlace(page, "From", VENUE);
  await page.getByLabel("Planned local time").fill("2026-10-03T18:05");
  await page.getByRole("button", { name: "Compare my options" }).click();
  const update = page.getByRole("region", { name: "Update private journey" });
  await update.getByLabel("Remaining check-in (minutes)").fill("12");
  await update.getByRole("button", { name: "Review journey update" }).click();
  await expect(update).toContainText("the original start stays unchanged");
  expect(await readTimer()).toEqual(originalTimer);
  expect(await readChoice()).toEqual(originalChoice);
  await update.getByRole("button", { name: "Cancel", exact: true }).click();
  await expect(update.getByRole("button", { name: "Confirm journey update" })).toHaveCount(0);
  expect(await readTimer()).toEqual(originalTimer);
  expect(await readChoice()).toEqual(originalChoice);

  await update.getByRole("button", { name: "Review journey update" }).click();
  await update.getByRole("button", { name: "Confirm journey update" }).click();
  await expect(update.getByRole("status")).toContainText("Manually confirm the origin for your continued journey");
  expect(await readTimer()).toEqual(originalTimer);
  expect(await readChoice()).toEqual(originalChoice);
  expect(tripPosts).toBe(0); expect(geoCalls()).toBe(0);
  const continuedOrigin = update.getByRole("checkbox", { name: /I manually confirmed the origin for my continued journey/ });
  await expect(continuedOrigin).toHaveAccessibleName(new RegExp(VENUE.name));
  await continuedOrigin.check();
  await update.getByRole("button", { name: "Review journey update" }).click();
  expect(await readTimer()).toEqual(originalTimer);
  await update.getByRole("button", { name: "Confirm journey update" }).click();
  await expect(page).toHaveURL(/\/trip\/local$/);
  const updatedTimer = { version: 1, startedAt, dueAt: confirmedAt + 12 * 60_000 };
  expect(await readTimer()).toEqual(updatedTimer);
  const updatedChoice = await readChoice();
  expect(updatedChoice).toMatchObject({ optionId: null, progress: 0, checkedInAt: null, updatedAt: confirmedAt, savedAt: confirmedAt });
  expect(updatedChoice.context).not.toBe(originalChoice.context);
  await expect(page.getByRole("status").filter({ hasText: "Journey update confirmed at" })).toContainText("The original start is unchanged; nobody was notified");
  await expect(page.getByRole("heading", { name: "Your way around.", exact: true })).toBeVisible();
  await expect(page.getByRole("slider", { name: /Manual progress/ })).toHaveCount(0);

  await page.reload();
  await expect(page.getByRole("status").filter({ hasText: "Journey update confirmed at" })).toContainText("The original start is unchanged; nobody was notified");
  expect(await readTimer()).toEqual(updatedTimer);
  expect(await readChoice()).toEqual(updatedChoice);
  const retained = await page.evaluate(() => JSON.parse(sessionStorage.getItem("mira.plan.v1")!).draft);
  expect(retained.activity).toBe("Fictional continued loop");
  expect(retained.origin.query).toBe(VENUE.name);
  expect(retained.departureLocal).toBe("2026-10-03T18:05");
  await expect(page.getByRole("heading", { name: "You’ve arrived." })).toHaveCount(0);
  await page.getByRole("button", { name: "End journey early" }).click();
  await expect(page.getByRole("heading", { name: "Journey ended." })).toBeVisible();
  await expect(page.getByRole("status").filter({ hasText: "not recorded as arrival" })).toBeVisible();
  expect(await readTimer()).toBeNull(); expect(await readChoice()).toBeNull();
  expect(tripPosts).toBe(0); expect(geoCalls()).toBe(0);
});
