/**
 * Writes docs/COUNTRY_COVERAGE.md from the registry + cited profiles, and prints the summary.
 * Usage: npx tsx --tsconfig tsconfig.json scripts/country-coverage.ts [--check]
 * --check fails when the committed report is out of date (for CI).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { emergencyCoverage, loadCountryData } from "../src/server/locale/data";

const d = loadCountryData();
const cov = emergencyCoverage(d);
const name = (iso: string) => d.registry.find((c) => c.iso2 === iso)?.name ?? iso;
const list = (isos: string[]) => (isos.length ? isos.map((i) => `${name(i)} (${i})`).join(", ") : "none");
const n = (k: keyof typeof cov.byStatus) => cov.byStatus[k].length;
const represented = Object.values(cov.byStatus).flat().length;

const limits = [...cov.byStatus.PARTIALLY_VERIFIED, ...cov.byStatus.REGION_DEPENDENT]
  .map((iso) => `- **${name(iso)} (${iso})**, ${d.countryContext(iso).emergency.status}: ${d.countryContext(iso).emergency.limitations.join(" ")}`)
  .join("\n");

const reviewed = JSON.parse(readFileSync("data/locales/sources.json", "utf8")) as { tiers: Record<string, string>; hosts: Record<string, { authority: string; tier: number; note?: string }> };
const byTier = Object.entries(reviewed.tiers).map(([t, label]) => {
  const hosts = Object.entries(reviewed.hosts).filter(([, h]) => String(h.tier) === t);
  return `| ${t} | ${label} | ${hosts.length} |`;
});
const notes = Object.entries(reviewed.hosts).filter(([, h]) => h.note).map(([host, h]) => `- \`${host}\` (${h.authority}): ${h.note}`);

const md = `# Country coverage

Generated by \`scripts/country-coverage.ts\` from \`data/countries/registry.json\` and \`data/locales/\`. Do not edit by hand.

MIRA recognises every country and uses reviewed local emergency information where it has it. Local evidence coverage (routes, lighting, Help Points, safety updates) varies by source and area, and is separate from this report.

## Summary

\`\`\`
Countries represented: ${represented} / 195

Emergency:
Fully verified:      ${n("VERIFIED")}
Partially verified:  ${n("PARTIALLY_VERIFIED")}
Region-dependent:    ${n("REGION_DEPENDENT")}
Not yet verified:    ${n("UNVERIFIED")}
\`\`\`

Territories with a profile (not counted in the 195): ${cov.territories.map((t) => `${name(t.iso)} (${t.iso}) ${t.status}`).join(", ") || "none"}.

"Not yet verified" means MIRA has not reviewed an official source for that country yet. MIRA shows no number there, says so, and never substitutes 112, 911 or another country's number.

## Known limitations (partially verified and region-dependent)

${limits || "none"}

## Citation review

Every host cited by a profile is reviewed once in \`data/locales/sources.json\` against MIRA's source hierarchy; a profile citing an unreviewed host fails the tests. No travel blog, SEO site or crowdsourced list is cited.

| Tier | Source type | Hosts |
|---|---|---|
${byTier.join("\n")}

${notes.join("\n")}

## By status

- **Fully verified (${n("VERIFIED")})**: ${list(cov.byStatus.VERIFIED)}
- **Partially verified (${n("PARTIALLY_VERIFIED")})**: ${list(cov.byStatus.PARTIALLY_VERIFIED)}
- **Region-dependent (${n("REGION_DEPENDENT")})**: ${list(cov.byStatus.REGION_DEPENDENT)}
- **Not yet verified (${n("UNVERIFIED")})**: ${list(cov.byStatus.UNVERIFIED)}
`;

const out = "docs/COUNTRY_COVERAGE.md";
if (process.argv.includes("--check")) {
  if (readFileSync(out, "utf8") !== md) {
    console.error(`${out} is out of date: run scripts/country-coverage.ts`);
    process.exit(1);
  }
} else writeFileSync(out, md);
console.log(md.split("## Known")[0].split("## Summary")[1].trim());
