import { randomBytes } from "node:crypto";
import { existsSync, writeFileSync } from "node:fs";
import { hash } from "@node-rs/argon2";

/**
 * Generate an ignored .env.local for local development with fresh random secrets.
 * Refuses to overwrite an existing file unless --force is given.
 */
async function main() {
  const target = ".env.local";
  if (existsSync(target) && !process.argv.includes("--force")) {
    console.log(`${target} already exists; leaving it untouched (use --force to regenerate).`);
    return;
  }
  const adminPassword = randomBytes(18).toString("base64url");
  const adminHash = await hash(adminPassword, {
    algorithm: 2,
    memoryCost: 19456,
    timeCost: 2,
    parallelism: 1,
  });
  const lines = [
    "# Generated by `npm run env:local`. Local development only — never commit.",
    "DATABASE_URL=postgres://mira:mira_local_dev@127.0.0.1:54329/mira",
    "APP_BASE_URL=http://localhost:3100",
    `SESSION_SECRET=${randomBytes(32).toString("base64")}`,
    "# base64-encoded 32-byte AES-256-GCM key",
    `DATA_ENCRYPTION_KEY=${randomBytes(32).toString("base64")}`,
    "# Argon2id hash in b64: form (no $ characters, so dotenv can't mangle it).",
    `ADMIN_PASSWORD_HASH=b64:${Buffer.from(adminHash, "utf8").toString("base64")}`,
    "PILOT_MANIFEST_PATH=data/pilot/manifest.json",
    "# Placeholder basemap: OpenFreeMap vector style (free, no key; OSM data). Swap for Mapbox later.",
    "MAP_STYLE_URL=https://tiles.openfreemap.org/styles/positron",
    "MAP_TILE_URL=https://tile.openstreetmap.org/{z}/{x}/{y}.png",
    "MAP_TILE_ATTRIBUTION=© OpenStreetMap contributors",
    "# Mailpit (docker compose) captures all mail locally at http://localhost:8025",
    "SMTP_HOST=127.0.0.1",
    "SMTP_PORT=1025",
    "SMTP_FROM=MIRA <no-reply@mira.localhost>",
    "# Optional AI adapter stays disabled unless all three are set deliberately.",
    "OPENAI_API_KEY=",
    "OPENAI_MODEL=",
    "OPENAI_PRIVACY_TERMS_ACCEPTED=",
    "",
  ];
  writeFileSync(target, lines.join("\n"), { mode: 0o600 });
  console.log(`Wrote ${target} with fresh random secrets.`);
  console.log("\nLocal moderator password (shown once, not stored anywhere else):");
  console.log(`  ${adminPassword}\n`);
  console.log("Sign in at http://localhost:3100/admin/login");
}

main();
